server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fqc/cloud-config-repo
          search-paths: config
#          uri: https://github.com/fqc/bigdata_sidepro_new
#          searchPaths: spring-cloud-sidepro/cloud-config-repo/resources